import './globals.css'
import type { Metadata } from 'next'
import { Nunito } from 'next/font/google'
import clsx from 'clsx'
import { EditorProvider } from '@/providers/EditorProvidor'

const nunito = Nunito({ subsets: ['latin'] })

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<html lang="en">
			<head>
				<meta charSet="utf-8" />
				<title>Astroneer Save Editor</title>
				<meta
					name="description"
					content="Save Editor for Astroneer (UNFINISHED)"
				/>
			</head>
			<body className={clsx(nunito.className, 'h-screen w-full')}>
				<EditorProvider>{children}</EditorProvider>
			</body>
		</html>
	)
}
